### ISSUE TITLE
【Misson】UserController.phpの修正

### ISSUE THREAD

**Issue by majikarikeruo** [shihori-23/FashionClue#14]
随時書いていきますー（3/20）

## 1、editTaste関数内の余計な情報を消す
https://github.com/shihori-23/FashionClue/blob/6211231e6f1c2af962697cea6c71e6d13a315688/app/Http/Controllers/Api/UsersController.php#L90

この辺とか。

**Comment by shihori-23** [comment]
上記対応いたしました！
ご確認ありがとうございます＾＾

**Comment by majikarikeruo** [comment]
別対応するため一旦クローズ
