### ISSUE TITLE
【Mission】お気に入り登録・削除について

### ISSUE THREAD

**Issue by majikarikeruo** [shihori-23/FashionClue#20]
#

## お気に入りの登録・削除時にAPI側でsuccessしない場合の処理を追加する
エラーとか何か不足あった場合の処理はやっぱりあった方が良いので、追加する！

※参考記事
https://qiita.com/reflet/items/52a157008caf0c758863

対応内容としては
 - サーバサイドで上記記事のような処理を加える
- フロントエンド側でfalseだった場合の処理も一応加えておく。
ですかねー。
でもサーバサイド側では404加える処理になるだろうからaxiosではcatchの方書いてればよかったかも・・・確認しておきます。

## APIのURL変更
api/post/post_bookmark/
api/destory/post_bookmark/

ではなくて、

api/post_bookmark/post/
api/post_bookmark/destory/

にすべしかと！
URLの原則的にも1つのcontrollerに対して、何の機能が属しているのかを表す形にした方が
正しい表現になる。

## showメソッドは不要？？
BookmarkPostsController内のshowメソッドは

「質問詳細画面でお気に入りしているか確認」

するための意図として作成していると書かれていたのですが、
そうなるとhasManyとbelongToを活用することで、PostsControllerのshowメソッドの中で
一律に取得できるのかなぁという気がしました。

`$bookmarkData = Post::find($postId)->bookmarks()->where('post_id', $postId)->where('user_id', $user_id)->get();`

みたいな感じにすれば、1 or 0 で取得数が分かれてくると思うので、1ならtrue、0ならfalseにして、フロントにデータを返せばいけるかなぁと！

ちなみにこれをやるとsaveとdestroyも修正できると思われます。

## Controller側のbookmarkedDataShowとbookmarkedDataShowの2箇所について
ここ、join色々していただいていると思うのですが、ざっと見てみたところ、showメソッドと同様、リレーション正しくできていれば、同じノリでいけると思いました〜！

とはいえ、これはどっちを書きやすいととるか次第だと思うのですが、
一応リレーション活用するパターンでもいけるよーということは書いておきます〜〜〜

##（コスゲ調査中） home画面や質問詳細表示画面においてのお気に入りの追加・削除について
配列で管理されているんですがhomeについてもリレーション使えば、true or falseでもいけるような気がしました！
必ずやらなければいけないというものでもないので、時間あるときにでも調査していただければ〜

**Comment by shihori-23** [comment]
1. お気に入りの登録・削除時にAPI側でsuccessしない場合の処理を追加する
こちらは一旦catchでエラーのメッセージを表示する処理で対応しております。

**・APIのURL変更**
**・showメソッドの変更**
も対応してみたのですが、save/destroyメソッドはそのままにしております。

**Comment by majikarikeruo** [comment]
@shihori-23 
ありがとうございますー
確認していますー

この辺見ながら、フロントの人も最近はサーバサイドのこと多少なりともわかってないとダメだよなーと改めて思いました〜〜〜


AnserBookmarkComponent.vueなんかは
似た感じのbuttonを2つ書くことになっているので
例えばデータの値によって動くメソッドを変更するとか、
そういうことも出来そうですね。

```
    methods: {
        BookmarkOperationAtClick() {
            this.$emit("add-answer-bookmark");
        },
        removeBookmarkOperationAtClick() {
            this.$emit("remove-answer-bookmark");
        }
    }
```

ここを1つにまとめて、親に渡す値によって


```
        addAnswerBookmark: function(id) {
            axios
                .post("api/answer_bookmark/post/" + id)
                .then(res => {
                    console.log(res.data.isBookmarked);
                    const answerBookmarkIdArray = this.isBookmarkedId.answer;
                    answerBookmarkIdArray.push(id);
                    this.isBookmarkedId.answer = answerBookmarkIdArray;
                    console.log(this.isBookmarkedId.answer);
                })
                .catch(err => {
                    this.setBookmarkAxiosErrorData(err);
                });
        },
        // 回答に対するお気に入りの解除
        removeAnswerBookmark: function(id) {
            axios
                .post("api/answer_bookmark/destory/" + id)
                .then(res => {
                    console.log(res.data.bookmarksId);
                    this.isBookmarkedId.answer = res.data.bookmarksId;
                })
                .catch(err => {
                    this.setBookmarkAxiosErrorData(err);
                });
        },


```

ここを渡された値によってapiのパラメーターだけ変更して、
1つの関数にするとか・・・かな！？

postしてデータ返ってきたあとに実行するプログラムも
filter()とか使ってうまいことできるかなぁと思ってます。




一旦close扱いにします〜〜〜
