### ISSUE TITLE
【Mission】全体共通

### ISSUE THREAD

**Issue by majikarikeruo** [shihori-23/FashionClue#23]
## １、Mixinを使う
いわゆる、「コンポーネントをまたいで共通して使用しそうなメソッド」を定義する！！

https://jp.vuejs.org/v2/guide/mixins.html

使えそうな気がしたので、書いておきまーす

## ２、性別の部分のComponent化
`                  <span class="genderSpan">{{ gender[userProfileData.gender] }}</span>
`
っていうのがちょこちょこあると思うのですが、意外と管理ややこしそうなので、
ここだけコンポーネント化するとかどうでしょう？？

**Comment by shihori-23** [comment]
１、Mixinを使う
Mixinにエラーの際の処理などを定義してみました
共有ありがとうございます！

２、性別の部分のコンポーネント化
こちらもコンポーネント化してみました！アドバイスありがとうございます！

**Comment by majikarikeruo** [comment]
@shihori-23 
遅ればせながらありがとうございましたー
確認しています〜〜〜
closeDialog()とかlogout()もMixinが役立ちそうですね！

この辺って、PHPのClass内メソッド（LaravelでいうControllerに書くやつ）と共通関数（functions.phpとか作って中に書き込むやつ。たぶん授業でhtmlspecialcharasをどこでも使いまわせるようにした時にやったと思います）の違いとかに思想が似てるなぁと改めて思って、なんやかんやどこの言語も似たところあるんだなぁ〜〜って思いました！


事実上これで一旦close扱いにします〜〜〜
